### ISSUE TITLE
[GFA2] Variance field in Gap line should be optional

### ISSUE THREAD

**Issue by eshcherbin** [sjackman/gfalint#2]
Hi!
According to [specification](https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md) the variance field in a G-line can be `*`, whereas in [gfay.y](https://github.com/sjackman/gfalint/blob/master/gfay.y) it seems to be obligatory. Could you please change this or correct me if I'm wrong?
Thanks!

**Comment by sjackman** [comment]
Thanks for the bug report, Egor. I've fixed it.
